version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/ArkEcosystem/go-crypto
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run:
          name: Tests
          command: ./runtests.sh
      - run:
          name: Codecov
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)
